/**
 * @enum ROUTE_NAME
 */
export enum ROUTE_NAME {
  MAIN = 'MAIN',
  // Facturas
  FACTURA_HOME = 'FACTURA.HOME',
  FACTURA_DETAILS = 'FACTURA.DETAILS',
  // Entities
  ENTITY_HOME = 'ENTITY.HOME',
  // Phones
  PHONE_HOME = 'PHONE.HOME',
  PHONE_FORM = 'PHONE.INSERT',
  PHONE_SEARCH = 'PHONE.SEARCH',
  // Profile
  PROFILE_HOME = 'PROFILE.HOME',
  // Stats
  STATS_HOME = 'STATS.HOME',
}